### ISSUE TITLE
[Bug]: Issue starting agent after updating to 0.12.7 with homebrew on older Mac OS (High Sierra 10.13.6)

### ISSUE THREAD

**Issue by winstonstwn** [henrygd/beszel#1156]
### Component

Agent

### Description

From the output of `~/.cache/beszel/beszel-agent.log`:
```
dyld: Symbol not found: _SecTrustCopyCertificateChain
  Referenced from: /usr/local/Cellar/beszel-agent/0.12.7/bin/beszel-agent (which was built for Mac OS X 12.0)
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /usr/local/Cellar/beszel-agent/0.12.7/bin/beszel-agent
```

### Expected Behavior

It has been updating fine without issue up to 0.12.6 and downgrading it manually (fetching .rb for 0.12.6) it starts up normally again without any issues.

Logs from `~/.cache/beszel/beszel-agent.log` on manual downgrade to 0.12.6:
```
INFO Data directory path=/Users/myuser/.config/beszel
INFO Root disk mountpoint=/ io=disk0
INFO Detected network interface name=en0 sent=6616179723 recv=5849900816
INFO WebSocket connected host=beszel.mydomain.com
```

### Steps to Reproduce

1. `brew upgrade beszel-agent`
2. `brew services restart henrygd/beszel/beszel-agent`

### Category

Installation

### Affected Metrics

Other

### OS / Architecture

macOS/amd64 (agent)

### Beszel version

0.12.7

### Installation method

Other (please describe above)

### Configuration

```yaml
Env file config:

KEY="<ssh-key>"
LISTEN=45876
PRIMARY_SENSOR=TC0H
SENSORS=-TC0D,TC0P
HUB_URL=https://beszel.mydomain.com
TOKEN=<token>
```

### Hub Logs

```json
message:	System down
data.err:	dial tcp 192.168.1.146:45876: connect: connection refused
```

### Agent Logs

```shell

```

**Comment by henrygd** [comment]
Unfortunately it appears that Go 1.25+ now requires macOS 12 Monterey or later. Support for previous versions has been discontinued.

I'm not an Apple person -- is it impossible to upgrade those machines? We might try to stay on 1.24 a little while longer in that case.

**Comment by winstonstwn** [comment]
No worries, just wanted to confirm if it's indeed a breaking change. It's an old iMac (mid 2010) that I still use as a secondary monitor using target display mode. It natively only supports up to macOS 10.13.6, I can update it using Opencore but it breaks the target display mode so I just decided to stay on the last native supported version. 

If Go has to be updated sooner or later, I can just remain on version 0.12.6 for this machine instead of downgrading Go. As long as the future version of the hub is backwards compatible and still accepts connections to the outdated agent.
